In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('faa_ai_prelim.csv')

## View

In [3]:
df

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,No,08-FEB-16,31-DEC-15,17:00:00Z,SAN ANTONIO,Texas,NaN,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",Accident,FAA San Antonio FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,No,08-FEB-16,05-FEB-16,11:17:00Z,MARICOPA,Arizona,NaN,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Yes,02-FEB-16,02-FEB-16,01:52:00Z,MOBILE,Alabama,NaN,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,Accident,FAA Birmingham FSDO-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR', 'ACFT_OPRTR',
       'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_MISSING_FLAG',
       'ACFT_DMG_DESC', 'FLT_ACTIVITY', 'FLT_PHASE', 'FAR_PART', 'MAX_INJ_LVL',
       'FATAL_FLAG', 'FLT_CRW_INJ_NONE', 'FLT_CRW_INJ_MINOR',
       'FLT_CRW_INJ_SERIOUS', 'FLT_CRW_INJ_FATAL', 'FLT_CRW_INJ_UNK',
       'CBN_CRW_INJ_NONE', 'CBN_CRW_INJ_MINOR', 'CBN_CRW_INJ_SERIOUS',
       'CBN_CRW_INJ_FATAL', 'CBN_CRW_INJ_UNK', 'PAX_INJ_NONE', 'PAX_INJ_MINOR',
       'PAX_INJ_SERIOUS', 'PAX_INJ_FATAL', 'PAX_INJ_UNK', 'GRND_INJ_NONE',
       'GRND_INJ_MINOR', 'GRND_INJ_SERIOUS', 'GRND_INJ_FATAL', 'GRND_INJ_UNK'],
      dtype='object')

In [5]:
# Aircraft make name
df.ACFT_MAKE_NAME

0              BEECH
1               VANS
2             CESSNA
3            LANCAIR
4             CESSNA
           ...
78           AERONCA
79    NORTH AMERICAN
80          CHAMPION
81             BEECH
82            CESSNA
Name: ACFT_MAKE_NAME, Length: 83, dtype: object

In [6]:
# State name
df.LOC_STATE_NAME

0     North Carolina
1            Florida
2         New Jersey
3     North Carolina
4             Alaska
           ...
78             Texas
79           Arizona
80        California
81        California
82           Alabama
Name: LOC_STATE_NAME, Length: 83, dtype: object

In [7]:
# Aircraft model name
df.ACFT_MODEL_NAME

0        36
1       RV7
2       172
3       235
4       172
      ...
78     O58B
79      F51
80    8KCAB
81       35
82      182
Name: ACFT_MODEL_NAME, Length: 83, dtype: object

In [8]:
# Text information
df.RMK_TEXT

0     AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...
1     AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...
2     AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...
3     AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...
4     AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...
                            ...
78    AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...
79    AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...
80    N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...
81    N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...
82    N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...
Name: RMK_TEXT, Length: 83, dtype: object

In [9]:
# Flight phase
df.FLT_PHASE

0      UNKNOWN (UNK)
1      LANDING (LDG)
2     APPROACH (APR)
3      LANDING (LDG)
4      LANDING (LDG)
           ...
78     LANDING (LDG)
79     UNKNOWN (UNK)
80     UNKNOWN (UNK)
81     UNKNOWN (UNK)
82     UNKNOWN (UNK)
Name: FLT_PHASE, Length: 83, dtype: object

In [10]:
# Event type description
df.EVENT_TYPE_DESC

0     Accident
1     Incident
2     Incident
3     Incident
4     Incident
        ...
78    Accident
79    Accident
80    Accident
81    Accident
82    Accident
Name: EVENT_TYPE_DESC, Length: 83, dtype: object

In [11]:
# Fatal flag
df.FATAL_FLAG

0     Yes
1     NaN
2     NaN
3     NaN
4     NaN
     ...
78    NaN
79    Yes
80    Yes
81    Yes
82    Yes
Name: FATAL_FLAG, Length: 83, dtype: object

## EDA

In [12]:
# Finding number of NaN values in each column
df.isna().sum()

UPDATED                 0
ENTRY_DATE              0
EVENT_LCL_DATE          0
EVENT_LCL_TIME          0
LOC_CITY_NAME           0
LOC_STATE_NAME          0
LOC_CNTRY_NAME         81
RMK_TEXT                0
EVENT_TYPE_DESC         0
FSDO_DESC               2
REGIST_NBR              0
FLT_NBR                77
ACFT_OPRTR             76
ACFT_MAKE_NAME          5
ACFT_MODEL_NAME         4
ACFT_MISSING_FLAG      83
ACFT_DMG_DESC           1
FLT_ACTIVITY           70
FLT_PHASE               1
FAR_PART               82
MAX_INJ_LVL             3
FATAL_FLAG             75
FLT_CRW_INJ_NONE       19
FLT_CRW_INJ_MINOR      77
FLT_CRW_INJ_SERIOUS    82
FLT_CRW_INJ_FATAL      75
FLT_CRW_INJ_UNK        83
CBN_CRW_INJ_NONE       83
CBN_CRW_INJ_MINOR      83
CBN_CRW_INJ_SERIOUS    83
CBN_CRW_INJ_FATAL      83
CBN_CRW_INJ_UNK        82
PAX_INJ_NONE           66
PAX_INJ_MINOR          82
PAX_INJ_SERIOUS        80
PAX_INJ_FATAL          82
PAX_INJ_UNK            83
GRND_INJ_NONE          83
GRND_INJ_MINOR         83
GRND_INJ_SERIOUS       83
GRND_INJ_FATAL         83
GRND_INJ_UNK           82
dtype: int64

In [13]:
# Replacing NaN values in Fatal flag with 'No'
df.FATAL_FLAG.fillna('No', inplace=True)

In [14]:
df.FATAL_FLAG

0     Yes
1      No
2      No
3      No
4      No
     ...
78     No
79    Yes
80    Yes
81    Yes
82    Yes
Name: FATAL_FLAG, Length: 83, dtype: object

In [15]:
# Replacing all NaN values in other columns with 'UNKNOWN'
df.fillna('UNKNOWN', inplace=True)

In [16]:
df.isna().sum()

UPDATED                0
ENTRY_DATE             0
EVENT_LCL_DATE         0
EVENT_LCL_TIME         0
LOC_CITY_NAME          0
LOC_STATE_NAME         0
LOC_CNTRY_NAME         0
RMK_TEXT               0
EVENT_TYPE_DESC        0
FSDO_DESC              0
REGIST_NBR             0
FLT_NBR                0
ACFT_OPRTR             0
ACFT_MAKE_NAME         0
ACFT_MODEL_NAME        0
ACFT_MISSING_FLAG      0
ACFT_DMG_DESC          0
FLT_ACTIVITY           0
FLT_PHASE              0
FAR_PART               0
MAX_INJ_LVL            0
FATAL_FLAG             0
FLT_CRW_INJ_NONE       0
FLT_CRW_INJ_MINOR      0
FLT_CRW_INJ_SERIOUS    0
FLT_CRW_INJ_FATAL      0
FLT_CRW_INJ_UNK        0
CBN_CRW_INJ_NONE       0
CBN_CRW_INJ_MINOR      0
CBN_CRW_INJ_SERIOUS    0
CBN_CRW_INJ_FATAL      0
CBN_CRW_INJ_UNK        0
PAX_INJ_NONE           0
PAX_INJ_MINOR          0
PAX_INJ_SERIOUS        0
PAX_INJ_FATAL          0
PAX_INJ_UNK            0
GRND_INJ_NONE          0
GRND_INJ_MINOR         0
GRND_INJ_SERIOUS       0
GRND_INJ_FATAL         0
GRND_INJ_UNK           0
dtype: int64

In [17]:
# Number of times each aircraft type appear in the dataset
df.ACFT_MODEL_NAME.value_counts()

172              4
UNKNOWN          4
210              4
PA28             3
35               3
150              3
206              3
PA34             3
36               3
M20K             2
PA24             2
182              2
8KCAB            2
310              2
152              2
737              2
M20E             1
560              1
EAGLE II         1
BT15             1
FIREFLY          1
T34              1
175              1
747              1
33               1
S2               1
140              1
55               1
CTLS             1
PA31             1
TB21             1
47G              1
235              1
340              1
RV7              1
PT19             1
KITFOX           1
A319             1
GULFSTREAM200    1
IV               1
180              1
PA20             1
TB9              1
AA1              1
M4               1
RX8              1
NA265            1
O58B             1
M20M             1
F51              1
369              1
2T1A             1
GC1B             1
500              1
ERJ190           1
Name: ACFT_MODEL_NAME, dtype: int64

In [18]:
# Removing the rows whose aircraft name is unkown
df.drop(df[df['ACFT_MAKE_NAME']=='UNKNOWN'].index, inplace=True)

In [19]:
df.ACFT_MAKE_NAME

0              BEECH
1               VANS
2             CESSNA
3            LANCAIR
4             CESSNA
           ...
78           AERONCA
79    NORTH AMERICAN
80          CHAMPION
81             BEECH
82            CESSNA
Name: ACFT_MAKE_NAME, Length: 78, dtype: object

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 78 entries, 0 to 82
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UPDATED              78 non-null     object
 1   ENTRY_DATE           78 non-null     object
 2   EVENT_LCL_DATE       78 non-null     object
 3   EVENT_LCL_TIME       78 non-null     object
 4   LOC_CITY_NAME        78 non-null     object
 5   LOC_STATE_NAME       78 non-null     object
 6   LOC_CNTRY_NAME       78 non-null     object
 7   RMK_TEXT             78 non-null     object
 8   EVENT_TYPE_DESC      78 non-null     object
 9   FSDO_DESC            78 non-null     object
 10  REGIST_NBR           78 non-null     object
 11  FLT_NBR              78 non-null     object
 12  ACFT_OPRTR           78 non-null     object
 13  ACFT_MAKE_NAME       78 non-null     object
 14  ACFT_MODEL_NAME      78 non-null     object
 15  ACFT_MISSING_FLAG    78 non-null     object
 16  ACFT_DMG_DESC        78 non-null     object
 17  FLT_ACTIVITY         78 non-null     object
 18  FLT_PHASE            78 non-null     object
 19  FAR_PART             78 non-null     object
 20  MAX_INJ_LVL          78 non-null     object
 21  FATAL_FLAG           78 non-null     object
 22  FLT_CRW_INJ_NONE     78 non-null     object
 23  FLT_CRW_INJ_MINOR    78 non-null     object
 24  FLT_CRW_INJ_SERIOUS  78 non-null     object
 25  FLT_CRW_INJ_FATAL    78 non-null     object
 26  FLT_CRW_INJ_UNK      78 non-null     object
 27  CBN_CRW_INJ_NONE     78 non-null     object
 28  CBN_CRW_INJ_MINOR    78 non-null     object
 29  CBN_CRW_INJ_SERIOUS  78 non-null     object
 30  CBN_CRW_INJ_FATAL    78 non-null     object
 31  CBN_CRW_INJ_UNK      78 non-null     object
 32  PAX_INJ_NONE         78 non-null     object
 33  PAX_INJ_MINOR        78 non-null     object
 34  PAX_INJ_SERIOUS      78 non-null     object
 35  PAX_INJ_FATAL        78 non-null     object
 36  PAX_INJ_UNK          78 non-null     object
 37  GRND_INJ_NONE        78 non-null     object
 38  GRND_INJ_MINOR       78 non-null     object
 39  GRND_INJ_SERIOUS     78 non-null     object
 40  GRND_INJ_FATAL       78 non-null     object
 41  GRND_INJ_UNK         78 non-null     object
dtypes: object(42)
memory usage: 26.2+ KB

In [21]:
#The observations with fatal flag 'Yes'
df1=df[df['FATAL_FLAG']=='Yes']
df1

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,UNKNOWN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
53,No,12-FEB-16,11-FEB-16,11:32:00Z,DESTIN,Florida,United States,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,Accident,UNKNOWN,...,UNKNOWN,UNKNOWN,UNKNOWN,1.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
55,No,11-FEB-16,11-FEB-16,00:17:00Z,TULARE,California,UNKNOWN,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,Accident,FAA Fresno FSDO-17,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
79,No,08-FEB-16,05-FEB-16,11:17:00Z,MARICOPA,Arizona,UNKNOWN,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",Accident,FAA Scottsdale FSDO-07,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
80,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,UNKNOWN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
81,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,UNKNOWN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
82,Yes,02-FEB-16,02-FEB-16,01:52:00Z,MOBILE,Alabama,UNKNOWN,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,Accident,FAA Birmingham FSDO-09,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN

In [22]:
df1.FATAL_FLAG

0     Yes
53    Yes
55    Yes
79    Yes
80    Yes
81    Yes
82    Yes
Name: FATAL_FLAG, dtype: object

In [23]:
df.reset_index(drop=True)

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,UNKNOWN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,UNKNOWN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,UNKNOWN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,UNKNOWN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,UNKNOWN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,UNKNOWN,1.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,No,08-FEB-16,31-DEC-15,17:00:00Z,SAN ANTONIO,Texas,UNKNOWN,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",Accident,FAA San Antonio FSDO-17,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
74,No,08-FEB-16,05-FEB-16,11:17:00Z,MARICOPA,Arizona,UNKNOWN,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",Accident,FAA Scottsdale FSDO-07,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
75,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,UNKNOWN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
76,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,UNKNOWN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
77,Yes,02-FEB-16,02-FEB-16,01:52:00Z,MOBILE,Alabama,UNKNOWN,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,Accident,FAA Birmingham FSDO-09,...,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN